package dev.offlical.mccd;

public enum CDType {
   
	REGENHP("REGENHP"),
	BREAK("BREAK"),PLACE("PLACE"),MOVE_HORZ("MOVE_HORZ")
	,MOVE_UP("MOVE_UP"),EGG_THROW("EGG_THROW"),DROP_ITEM("DROP_ITEM")
	,INTERACT_RIGHT("INTERACT_RIGHT"),INTERACT_LEFT("INTERACT_LEFT"),DAMAGE_ENTITY("DAMAGE_ENTITY"),CRAFT("CRAFT"),BOW_SHOT("BOW_SHOT"),BUCKET("BUCKET"),BUCKET_EMPTY("BUCKET_EMPTY"),
	IGNITE("IGNITE"),BLOCK_DAMAGE("BLOCK_DAMAGE"),CONSUME("CONSUME"),
	PICKUP_ITEM("PICKUP_ITEM");
	
 
	public final String label;
	
	private CDType(String s) {
		this.label = s;
	}
    
}